### ISSUE TITLE
Cannot press Authorize

### ISSUE THREAD

**Issue by Naatan** [densebrain/epictask#185]
The authorize button when logging in with GitHub appears to be disabled despite everything else being correct. Can I toggle dev tools somehow to investigate?

**Comment by Kennyboy7** [comment]
Bump ** it's the same for me

**Comment by Britz** [comment]
Same for me, using the mac version as Zip download (Version 1.0.15) on macOS High Sierra (Version 10.13.5). 

Login to github worked, but the `Authorize densebrain` button ist disabled (light green) as shown on the screenshot. It also mentions, that the used browser is no longer supported, perhaps that's the reason. 

![Screenshot](https://user-images.githubusercontent.com/2488427/42209263-81d01b08-7eae-11e8-9770-166756e9625a.png)
